name: Docker Image CI

on:
  push:
    branches:
      - master
      - uat
      - production
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to build'
        required: true
        default: 'master'
        type: choice
        options:
          - master
          - uat
          - production

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}  # Use selected branch for checkout

    - name: Set up Docker image tag based on branch
      id: vars
      run: |
        if [ "${{ github.event.inputs.branch }}" == "production" ]; then
          echo "IMAGE_TAG=production:$(date +%s)" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.branch }}" == "uat" ]; then
          echo "IMAGE_TAG=uat:$(date +%s)" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=test:$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Send success notification to Slack
      if: success()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
        BRANCH_NAME: "${{ github.event.inputs.branch }}"
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\"Docker build completed successfully on branch: $BRANCH_NAME! Built image tag: $IMAGE_TAG\"}" \
        $SLACK_WEBHOOK_URL

    - name: Send failure notification to Slack
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        BRANCH_NAME: "${{ github.event.inputs.branch }}"
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\"⚠️ Docker build failed on branch: $BRANCH_NAME! Please check the pipeline logs for details.\"}" \
        $SLACK_WEBHOOK_URL
